version: '3.5'

services:
  gateway:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    networks:
      - gateway
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  front:
    image: kgolezardi/performance-review-web:latest
    networks:
      - gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`${SITE_DOMAIN}`)"
      - "traefik.http.routers.front.priority=10"

  statics:
    image: kgolezardi/performance-review-statics:latest
    networks:
      - gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.statics.rule=Host(`${ADMIN_DOMAIN}`) && PathPrefix(`/django-statics/`)"
      - "traefik.http.routers.statics.priority=20"

  api:
    image: kgolezardi/performance-review-api:latest
    networks:
      - app_net
      - gateway
    depends_on:
      - database
    environment:
      - DEBUG
      - SECRET_KEY
      - DATABASE_URL
      - ALLOWED_HOSTS
      - CORS_ALLOW_CREDENTIALS
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${SITE_DOMAIN}`) && PathPrefix(`/graphql`)"
      - "traefik.http.routers.api.priority=30"
      - "traefik.http.routers.admin.rule=Host(`${ADMIN_DOMAIN}`)"
      - "traefik.http.routers.admin.priority=10"


  database:
    image: postgres:12.1
    networks:
      - app_net
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:

networks:
  gateway:
    name: "gateway"
    ipam:
      driver: default
      config:
        - subnet: ${GATEWAY_SUB_NET}
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${APP_SUB_NET}
