name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install poetry
        poetry config virtualenvs.create false
        (cd backend/review && poetry install -n --no-dev)
    - name: Check schema and collect statics
      run: |
        (cd backend/review && cp sample.env .env && python manage.py graphql_schema --out schema.graphql)
        git diff --exit-code --name-only
        (cd backend/review && cp sample.env .env && python manage.py collectstatic)
