# Generated by Django 4.2.6 on 2023-10-20 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0043_auto_20220728_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('help_text', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='personreview',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='personreview',
            name='created_at',
        ),
        migrations.AddField(
            model_name='personreview',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='personreview',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.CreateModel(
            name='CompetenciesAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rating', models.IntegerField(choices=[(1, 'LEVEL_1'), (2, 'LEVEL_2'), (3, 'LEVEL_3'), (4, 'LEVEL_4'), (5, 'LEVEL_5')], null=True)),
                ('evidence', models.TextField()),
                ('is_target', models.BooleanField(blank=True, default=False)),
                ('competencies', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.competencies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
