# Generated by Django 4.2.6 on 2023-10-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_competencies_alter_personreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='max_competency_target',
            field=models.IntegerField(default=2),
        ),
    ]
