# Generated by Django 4.2.6 on 2023-11-28 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0045_round_max_competency_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciesanswers',
            name='rating',
            field=models.FloatField(
                choices=[(1, 'LEVEL_1'), (1.5, 'LEVEL_1_5'), (2, 'LEVEL_2'), (2.5, 'LEVEL_2_5'), (3, 'LEVEL_3'),
                         (3.5, 'LEVEL_3_5'), (4, 'LEVEL_4'), (4.5, 'LEVEL_4_5'), (5, 'LEVEL_5')], null=True),
        ),
        migrations.CreateModel(
            name='PersonReviewMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentioned_person_reviews',
                                   to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                           related_name='author_mention_person_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
