# Generated by Django 4.2.6 on 2023-12-29 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0046_alter_competenciesanswers_rating_personreviewmention'),
    ]

    operations = [
        migrations.AddField(
            model_name='personreview',
            name='mention_users',
            field=models.ManyToManyField(blank=True, related_name='person_reviews_to_comment',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PersonReviewMention',
        ),
    ]
