# Generated by Django 4.2.6 on 2024-01-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0047_personreview_mention_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personreview',
            name='strength',
            field=models.TextField(blank=True, null=True),
        ),
    ]
